#!/bin/sh
# user dependent .bashrc file

source "${HOME}/app/sec/api-keys"

# if not running interactively, 
#  only read secure data into environment
[[ "$-" != *i* ]] && return

# override path by user and setup executeables
PATH="${PATH}:${HOME}/app/exe:${HOME}/dot/utils:${HOME}/app/dat/x/stp/current/exe"

source "${HOME}/app/dat/x/stp/current/conf"

printf '' > "${HOME}/.bash_login"

eval $(dircolors -b $HOME/.dircolors)

printf '[%s] Loading configs ...\n' "$(date +'%X')" | tee -a "${HOME}/.bash_login"
for p in "${HOME}/app/cnf/bash/run/"* ; do
  if [[ -x "${p}" ]]; then
    bn=$(basename "${p}" | cut -d '_' -f 2)
    printf '[%s] Sourcing %s ...\n' "$(date +'%X')" "${bn}" | tee -a "${HOME}/.bash_login"
    source "${p}"
  fi
done

test ! -z "${DISPLAY}" || test "$(tty)" != /dev/tty1 && prompt_message_handle
