#!/bin/sh
# user dependent .bashrc file

source "${HOME}/app/sec/api-keys"

# if not running interactively, 
#  only read secure data into environment
[[ "$-" != *i* ]] && return

# setup variables
SETUP_NAME='basic'
THEME_NAME='hotel'

# override path by user and setup executeables
PATH="${PATH}:${HOME}/dot/utils:${HOME}/app/cnf/x/lib:${HOME}/app/dat/x/stp/${SETUP_NAME}/exe:${HOME}/app/dat/x/stp/${SETUP_NAME}/wm2"

export SETUP_NAME THEME_NAME PATH

printf '' > "${HOME}/.bash_login"

eval $(dircolors -b $HOME/.dircolors)

printf '[%s] Loading configs ...\n' "$(date +'%X')" | tee -a "${HOME}/.bash_login"
for p in "${HOME}/app/cnf/bash/run/"* ; do
  if [[ -x "${p}" ]]; then
    bn=$(basename "${p}" | cut -d '_' -f 2)
    printf '[%s] Sourcing %s ...\n' "$(date +'%X')" "${bn}" | tee -a "${HOME}/.bash_login"
    source "${p}"
  fi
done

test ! -z "${DISPLAY}" || test "$(tty)" != /dev/tty1 && prompt_message_handle
