#!/usr/bin/env sh
# ii-console

params="${@}"

while test $# -gt 0; do
  case "$1" in
    -s|--server) export II_SERVER="${2}"; shift 2;;
    -c|--channel) export II_CHANNEL="${2}"; shift 2;;
    -n|--nick) export II_NICK="${2}"; shift 2;;
    -f|--friend) export II_FRIEND="${2}"; shift 2;;
    *) printf 'Invalid param: %s' "${1}"; exit 1;;
  esac
done
export II_SERVER="${II_SERVER:-irc.freenode.net}"
export II_DIR="${II_DIR:-$HOME/app/dat/irc}"

test -z "${II_NICK}" && printf 'Missing nick!' && exit 1
#test -z "${II_CHANNEL}" && printf 'Missing channel!' && exit 1


II_COLOR_SPLIT='\033[2m'
II_COLOR_STAT='\033[2m'
II_COLOR_SELF='\033[0;34m'
II_COLOR_NICK='\033[0;33m'
II_COLOR_TEXT='\033[0m'
II_COLOR_MENT="\033[0;32m"
II_COLOR_RESET='\033[0m'

read_line() {
  user=$(echo "${1}" | awk -F ' ' '{print $3}' | tr -d '<>')
  text=$(echo "${1}" | cut -d " " -f 4- | tr -dc '[[:print:]]')
  self=$(printf '%s' "${user}" | grep -q "${II_NICK}"; echo "$?")
  ment=$(printf '%s' "${text}" | grep -q "${II_NICK}"; echo "$?")
  sysm=$(test "${user}" != '-!-'; echo "$?")

  if printf '%s' "${text}" | grep -q -e '^ACTION '; then
    text=$(printf '%s' "${text}" | sed 's|^ACTION ||')
    spt="${II_COLOR_SPLIT} * ${II_COLOR_RESET}"
  else
    spt="${II_COLOR_SPLIT} » ${II_COLOR_RESET}"
  fi

  if test "${self}" -eq 0; then
    user="${II_COLOR_SELF}${user}${II_COLOR_RESET}"
  else
    user="${II_COLOR_NICK}${user}${II_COLOR_RESET}"
  fi

  if test "${sysm}" -eq 0; then
    if test "${ment}" -eq 0; then
      notify-send -u low " ${II_CHANNEL}"
      text="${II_COLOR_MENT}${text}${II_COLOR_RESET}"
    else
      text="${II_COLOR_TEXT}${text}${II_COLOR_RESET}"
    fi
    printf ' %-25b%b%b\n' "${user}" "${spt}" "${text}"
  else
    act=$(echo "${text}" | grep -o -e 'joined\|left\|mode')
    if test "${act}" = 'joined' || test "${act}" = 'left'; then
      user=$(echo "${text}" | cut -d '(' -f 1)
      printf ' %-14b%b%b\n' "" "${spt}" "${II_COLOR_STAT}${user} ${act}${II_COLOR_RESET}"
    fi
  fi
}

clear

# disable user input & invisible cursor
stty -echo; tput civis

# reset modi after quit
trap 'stty echo; tput cnorm' HUP INT TERM

i2r | while IFS= read -r line; do
  read_line "${line}"
done