#!/bin/sh

# COLOR: Status
ACTV_COLR="base05"
DISB_COLR="base03"
ERRO_COLR="base08"
INFO_COLR="base0D"
NORM_COLR="base05"
NTCE_COLR="base0A"
WARN_COLR="base09"
# COLOR: Font & AREA
BACK_COLR="base04"
FONT_COLR="base05"
# FONT
MONO_FONT="Fira Code"
MONO_SIZE="11"
NORM_FONT="Monaco"
NORM_SIZE="11"
SYMB_FONT="FontAwesome"
SYMB_SIZE="11"
# GTK
CURS_THME=""
ICON_THME=""
WIND_THME=""
# WALL
WALL_COLR="base02"
WALL_IMAG=""