#!/usr/bin/env sh
# ii-console

test -z "${II_NICK}" && printf 'Missing nick!' && exit 1
#test -z "${II_CHANNEL}" && printf 'Missing channel!' && exit 1

# reset modi after quit
trap 'stty echo; tput cnorm' HUP INT TERM

II_COLOR_SPLIT='\033[2m'
II_COLOR_STAT='\033[2m'
II_COLOR_SELF='\033[0;31m'
II_COLOR_NICK='\033[0;33m'
II_COLOR_TEXT='\033[0m'
II_COLOR_MENT="\033[0;32m"
II_COLOR_RESET='\033[0m'

cols=$(tput cols)
cols=$((cols - 20))

read_line() {
  user=$(echo "${1}" | awk -F ' ' '{print $3}' | tr -d '<>')
  text=$(echo "${1}" | cut -d " " -f 4- | tr -dc '[[:print:]]')
  self=$(printf '%s' "${user}" | grep -q "${II_NICK}"; echo "$?")
  ment=$(printf '%s' "${text}" | grep -q "${II_NICK}"; echo "$?")
  sysm=$(test "${user}" != '-!-'; echo "$?")

  if printf '%s' "${text}" | grep -q -e '^ACTION '; then
    text=$(printf '%s' "${text}" | sed 's|^ACTION ||')
    spt="${II_COLOR_SPLIT} : ${II_COLOR_RESET}"
  elif test "${sysm}" -eq 1; then
    spt="${II_COLOR_SPLIT} ± ${II_COLOR_RESET}"
  else
    spt="${II_COLOR_SPLIT} » ${II_COLOR_RESET}"
  fi

  if test "${self}" -eq 0; then
    user="${II_COLOR_SELF}${user}${II_COLOR_RESET}"
  else
    user="${II_COLOR_NICK}${user}${II_COLOR_RESET}"
  fi

  if test "${sysm}" -eq 0; then
    spac="                  "
    #text=$(echo "${text}"| sed -e "s/.\{${cols}\}/&\n${spac}/g")
    text=$(echo "${text}" | fold -w "${cols}" -s | sed -e "1!s/^/${spac}/")
    if test "${ment}" -eq 0; then
      #notify-send -u low " ${II_CHANNEL}"
      text="${II_COLOR_MENT}${text}${II_COLOR_RESET}"
    else
      text="${II_COLOR_TEXT}${text}${II_COLOR_RESET}"
    fi
    printf ' %-25b%b%b\n' "${user}" "${spt}" "${text}"
  else
    user=$(echo "${text}" | cut -d '(' -f 1)
    act=$(echo "${text}" | grep -o -e 'joined\|left\|mode\|quit')
    if test "${act}" != 'mode'; then
      printf ' %-14b%b%b\n' "" "${spt}" "${II_COLOR_STAT}${user} ${act}${II_COLOR_RESET}"
    fi
  fi
}

# disable user input & invisible cursor
stty -echo; tput civis

i2r | while IFS= read -r line; do
  read_line "${line}"
done
