#!/usr/bin/env sh
# ii-reader

test -z "${II_HISTORY}" && II_HISTORY=$(tput lines)

if test -z "${II_CHANNEL}"; then
  if ! test -z "${II_FRIEND}"; then
    test -d "${II_DIR}/${II_SERVER}/${II_FRIEND}" || exit 1
    tail -n "${II_HISTORY}" -f "${II_DIR}/${II_SERVER}/${II_FRIEND}/out"
  else
    test -d "${II_DIR}/${II_SERVER}" || exit 1
    tail -n "${II_HISTORY}" -f "${II_DIR}/${II_SERVER}/out"
  fi
else
  test -d "${II_DIR}/${II_SERVER}/#${II_CHANNEL}" || exit 1
  tail -n "${II_HISTORY}" -f "${II_DIR}/${II_SERVER}/#${II_CHANNEL}/out"
fi
