#!/usr/bin/env sh
# ii-writer

test -L "${II_CURCHAN}" && test -z "${II_CHANNEL}" && II_CHANNEL=$(basename $(realpath "${II_CURCHAN}") | tr -d '#')
test -z "${II_MESSAGE}" && II_MESSAGE=$(cat)

#printf '%s: %s\n' "${II_CHANNEL}" "${II_MESSAGE}"
#exit 1

if test -z "${II_CHANNEL}"; then
  if ! test -z "${II_FRIEND}"; then
    test -d "${II_DIR}/${II_SERVER}/${II_FRIEND}" || exit 1
    printf '%s\n' "${II_MESSAGE}" > "${II_DIR}/${II_SERVER}/${II_FRIEND}/in"
  else
    test -d "${II_DIR}/${II_SERVER}" || exit 1
    printf '%s\n' "${II_MESSAGE}" > "${II_DIR}/${II_SERVER}/in"
  fi
else
  test -d "${II_DIR}/${II_SERVER}/#${II_CHANNEL}" || exit 1
  printf '%s\n' "${II_MESSAGE}" > "${II_DIR}/${II_SERVER}/#${II_CHANNEL}/in"
fi
