#!/bin/sh

ntr | xlb -d -p -n 'sp' -g "x${PAD_TOP}" &
nPID=$!

#xdo id -p "${nPID}"

while ! xdo id -a 'sp' > /dev/null; do
  sleep 0.001
done

winID=$(xdo id -a 'sp')
ignw -s "${winID}"
#ROOT=$(lsw -r)
#SW=$(wattr w $ROOT)
#SH=$(wattr h $ROOT)
#wtp 0 0 "${SW}" 25 "${winID}"
#chwb -s 0 "${winID}"

while kill -0 "${nPID}"; do
  sleep 1
  test -s "${NOTIFY_CACHE}" && ! wattr m "${winID}" && mapw -m "${winID}"
  test ! -s "${NOTIFY_CACHE}" && wattr m "${winID}" && mapw -u "${winID}"
done
