#!/bin/sh

eval "$(x2v)"

# refresh bspwm
#~/app/cnf/bspwm/bspwmrc

# refresh bar
pgrep ntw >/dev/null && pkill ntw
pgrep ntb >/dev/null && pkill ntb
pgrep ntr >/dev/null && pkill ntr
pgrep lemonbar >/dev/null && pkill lemonbar

# refresh dunst
pgrep xdn >/dev/null && pkill xdn
pgrep dunst >/dev/null && pkill dunst

# refresh compton
pgrep compton >/dev/null && pkill compton

ntb &
ntw &
xdn -conf "${HOME}/app/cnf/dunst/dunstrc" &
compton --config "${HOME}/app/cnf/compton/compton.conf" &

setroot -z "${HOME}/app/dat/x/thm/current/wall/"*
