#!/bin/env sh

fp="${HOME}/usr/med/img/scr/$(date +'%x-%X').png"

if test "${1}" = 'area'; then
  maim -s -c 0.1,0.05,0.3,1 "${fp}"
#elif test "${1}" = 'window'; then
  #maim -i $(xdotool getactivewindow) "${fp}"
elif test "${1}" = 'desktop'; then
  maim "${fp}"
fi

test $? -eq 0 && printf '%s' "${fp}" && notify-send -u 'low' " ${1}"