#!/bin/sh

export HISTSIZE=5000
export HISTFILESIZE=10000

export LESSHISTSIZE=0

shopt -s histappend
export HISTTIMEFORMAT="%x %X "

#export HISTCONTROL="ignoreboth:erasedups"
export PROMPT_COMMAND="history -a;${PROMPT_COMMAND}"