#!/bin/sh

eval "$(x2v)"

bspc config active_border_color "${base05}"
bspc config focused_border_color "${base09}"
bspc config normal_border_color "${base03}"

prmr=$(xrandr | grep primary | awk -F ' ' '{print $1}')
bspc monitor "${prmr}" --reset-desktops 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config split_ratio 0.50
bspc config top_padding 20

bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config focus_by_distance true
#bspc config history_aware_focus true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true