#!/bin/sh

# Read Xresources for colors
eval "$(x2v)"

color00=$(printf '%s' "${base00}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color01=$(printf '%s' "${base0B}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color02=$(printf '%s' "${base0E}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color03=$(printf '%s' "${base0D}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color04=$(printf '%s' "${base09}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color05=$(printf '%s' "${base0F}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color06=$(printf '%s' "${base08}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color07=$(printf '%s' "${base05}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color08=$(printf '%s' "${base03}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color09="${color01}"
color10="${color02}"
color11="${color03}"
color12="${color04}"
color13="${color05}"
color14="${color06}"
color15=$(printf '%s' "${base0B}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color16=$(printf '%s' "${base0E}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color17=$(printf '%s' "${base0D}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color18=$(printf '%s' "${base09}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color19=$(printf '%s' "${base0F}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color20=$(printf '%s' "${base07}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color21=$(printf '%s' "${base06}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color_foreground=$(printf '%s' "${base04}" | tr -d '#' | sed 's/.\{2\}/&\//g')
color_background=$(printf '%s' "${base00}" | tr -d '#' | sed 's/.\{2\}/&\//g')

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
elif [ "${TERM%%-*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033P\033]%s%s\033\\' $@; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi

# 16 color space
put_template 0  $color00
put_template 1  $color01
put_template 2  $color02
put_template 3  $color03
put_template 4  $color04
put_template 5  $color05
put_template 6  $color06
put_template 7  $color07
put_template 8  $color08
put_template 9  $color09
put_template 10 $color10
put_template 11 $color11
put_template 12 $color12
put_template 13 $color13
put_template 14 $color14
put_template 15 $color15

# 256 color space
put_template 16 $color16
put_template 17 $color17
put_template 18 $color18
put_template 19 $color19
put_template 20 $color20
put_template 21 $color21

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  exit 0
else
  put_template_var 10 $color_foreground
  if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
    put_template_var 11 $color_background
    if [ "${TERM%%-*}" = "rxvt" ]; then
      put_template_var 708 $color_background # internal border (rxvt)
    fi
  fi
  put_template_custom 12 ";7" # cursor (reverse video)
fi

# clean up
unset -f put_template
unset -f put_template_var
unset -f put_template_custom
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
