#!/bin/sh
# void-container-manager

scriptDir=$(dirname `realpath -P "$0"`)
parentDir=$(dirname "${scriptDir}")

vcm_attach() {
  if ! test -f "${cntDir}/pid" || ! kill -0 $(cat "${cntDir}/pid") > /dev/null 2>&1; then
    printf '[%s] Container %s is not running!\n' "$(date +'%X')" "${cntName}"
    test -f "${cntDir}/pid" && rm "${cntDir}/pid"
    exit 1
  fi

  printf '[%s] Resuming screen %s ...\n' "$(date +'%X')" "cnt-${cntName}"
  screen -r "cnt-${cntName}"

  if ! kill -0 $(cat "${cntDir}/pid") > /dev/null 2>&1 ; then
    printf '[%s] Screen %s closed!\n' "$(date +'%X')" "cnt-${cntName}"
    rm "${cntDir}/pid"
  fi
}

vcm_create() {
  test -z "${cntName}" && cntName="${1:-$(date +'%Y%m%d-%H%M%S')}"

  if test -d "${cntDir}"; then
    printf '[%s] Container %s already exists!\n' "$(date +'%X')" "${cntName}"
    exit 1
  fi

  printf '[%s] Creating container directory %s ...\n' "$(date +'%X')" "${cntDir}"
  sudo mkdir -p "${cntDir}" || exit 1

  printf '[%s] Setting permissions on %s to %s:%s ...\n' "$(date +'%X')" "${cntName}" "${USER}" "${USER}"
  sudo chown -R "${USER}:${USER}" "${cntDir}" || exit 1

  printf '[%s] Entering container %s ...\n' "$(date +'%X')" "${cntName}"
  cd "${cntDir}" || exit 1

  if test 1 -eq 1; then
    printf '[%s] Copying xbps-confs ...\n' "$(date +'%X')"
    mkdir -p "${cntDir}/var/db/xbps/keys" "${cntDir}/usr/share"
    cp -a /usr/share/xbps.d "${cntDir}/usr/share/"
    cp /var/db/xbps/keys/*.plist "${cntDir}/var/db/xbps/keys"

    printf '[%s] Installing base-files ...\n' "$(date +'%X')"
    xbps-install -r "${cntDir}" -Sy base-files > "${cntDir}/vcm.log" || exit 1

    printf '[%s] Configuring base-files ...\n' "$(date +'%X')"
    xbps-reconfigure -r "${cntDir}" -f base-files > "${cntDir}/vcm.log" || exit 1

    printf '[%s] Installing remaining packages from %s ...\n' "$(date +'%X')" "${cntPkgs}"
    xbps-install -r "${cntDir}" -y $(cat "${cntPkgs}" | tr '\n' ' ') > "${cntDir}/vcm.log" || exit 1

    test -f "${cntDir}/vcm.log" && rm "${cntDir}/vcm.log"
    #for pkgName in $(cat "${cntPkgs}"); do
    #  printf '[%s] Installing %s ...\n' "$(date +'%X')" "${pkgName}"
    #  xbps-install -r "${cntDir}" "${pkgName}"
    #done
  else
    printf '[%s] Creating container image ...\n' "$(date +'%X')"
    tar -c -f - -C / usr | pseudo tar -x -f -

    printf '[%s] Creating symlinks ...\n' "$(date +'%X')"
    ln -s usr/bin bin
    ln -s usr/lib lib
    ln -s usr/lib lib64
    ln -s usr/lib32 lib32
    ln -s usr/sbin sbin
  fi
}

vcm_destroy() {
  printf '[%s] Are you sure to destroy %s? ...\n' "$(date +'%X')" "${cntName}"
  read -p ': ' answ

  case "${answ}" in
    y|Y|yes|YES) sudo rm -rf "${cntDir}"; printf '[%s] Container %s has been destroyed ...\n' "$(date +'%X')" "${cntName}";;
  esac
}

vcm_help() {
  cat <<EOT
Usage: $(basename $0) <action> [opts]

ACTIONS
  [a]ttach      Attach to a running container session
  [c]reate      Create a new container
  [d]estroy     Destroy existing container
  [i]nstall     Install pkg in container
  [l]ist        List all existing containers
  [r]un         Run container
  [s]top        Stop container
  [u]ninstall   Uninstall pkg from container

ENV-VARS
  cntName, cntDir, cntPkgs
EOT
  exit 1
}

vcm_inject() {
  if ! test -f "${cntDir}/pid" || ! kill -0 $(cat "${cntDir}/pid") > /dev/null 2>&1; then
    printf '[%s] Container %s is not running!\n' "$(date +'%X')" "${cntName}"
    exit 1
  fi

  printf '[%s] Injecting into %s with %s \n' "$(date +'%X')" "${cntName}" "${@}"
  inject $(cat "${cntDir}/pid") ${@}
}

vcm_install() {
  xbps-install -r "${cntDir}" ${@}
}

vcm_list() {
  printf '[%s] Listing containers ...\n' "$(date +'%X')"
  find '/data/vrt/cnt' -mindepth 1 -maxdepth 1 -type d | sed 's|/data/vrt/cnt/||g'
}

vcm_run() {
  if test -f "${cntDir}/pid"; then
    cntPID=$(cat "${cntDir}/pid")
    kill -0 "${cntPID}" > /dev/null 2>&1 || rm "${cntDir}/pid"
  fi

  if test -f "${cntDir}/pid"; then
    printf '[%s] Container %s already running under PID %s ...\n' "$(date +'%X')" "${cntName}" "${cntPID}"
    printf '[%s] Resume screen session %s!\n' "$(date +'%X')" "cnt-${cntName}"
    exit 1
  fi

  printf '[%s] Running container as screen session %s ...\n' "$(date +'%X')" "cnt-${cntName}"
  (cd "${cntDir}" && screen -d -m -S "cnt-${cntName}" /bin/sh -c 'contain . /bin/sh' && sleep 0.1)

  cntPID=$(screen -ls "cnt-${cntName}" | grep 'tached' | awk -F '.' '{print $1}' | grep -o '[0-9]*')
  if test -z "${cntPID}"; then
    printf '[%s] Container %s did not start!\n' "$(date +'%X')" "${cntName}"
    test -f "${cntDir}/pid" && rm "${cntDir}/pid"
    exit 1
  fi
  printf '[%s] Screen %s running as PID %s ...\n' "$(date +'%X')" "cnt-${cntName}" "${cntPID}"
  printf '%s' "${cntPID}" > "${cntDir}/pid"
}

vcm_stop() {
  printf '[%s] Stopping container %s ...\n' "$(date +'%X')" "${cntName}"
  screen -X -S "cnt-${cntName}" quit
}

vcm_uninstall() {
  xbps-remove -r "${cntDir}" -R ${@} | sed 's|^Removing|Removing (cnt)|g'
}

test $# -eq 0 && vcm_help
act="${1}"; shift

test -z "${cntName}" && test $(dirname "${PWD}") = '/data/vrt/cnt' && cntName=$(basename "${PWD}")

if test -z "${cntName}" && test $# -gt 0; then
  cntName="${1}"
  shift
fi

test -z "${cntDir}" && cntDir="/data/vrt/cnt/${cntName}"

if test ! -d "${cntDir}" && test "${act}" != 'c' && test "${act}" != 'l'; then
  printf '[%s] Container %s does not exist!\n' "$(date +'%X')" "${cntName}"
  exit 1
fi

test -z "${cntPkgs}" && cntPkgs="${parentDir}/conf/cnt.pkgs"

case "${act}" in
  a) vcm_attach ${@};;
  c) vcm_create ${@};;
  d) vcm_destroy ${@};;
  i) vcm_install ${@};;
  l) vcm_list ${@};;
  r) vcm_run ${@};;
  s) vcm_stop ${@};;
  u) vcm_uninstall ${@};;
esac