#!/usr/bin/env sh

test "$#" -eq 1 || exit 1

pid=$(xdo pid "${1}")
kill -0 "${pid}" || exit

# kill the process normally,
# wait for a second to shutdown and
# force termination if still active
kill "${pid}"
sleep 1
kill -0 "${pid}" && kill -8 "${pid}" && notify-send -u low " ${pid}"