#!/usr/bin/env sh

# roxe: react on x events
while IFS=: read ev wid; do
  case $ev in
    16) wattr o $wid || snaw c $wid;; # window creation
    18) grpw cln; wattr $(pfw) || focw his p;; # focus next window when deleting focused window
    19) wattr o $wid || focw $wid;; # mapping requests
    7) wattr o $wid || wtf $wid;; # entering window
  esac
done

# KEY_PRESS .......... 2
# KEY_RELEASE ........ 3
# BUTTON_PRESS ....... 4
# BUTTON_RELEASE ..... 5
# MOTION_NOTIFY ...... 6
# ENTER_NOTIFY ....... 7
# LEAVE_NOTIFY ....... 8
# FOCUS_IN ........... 9
# FOCUS_OUT .......... 10
# KEYMAP_NOTIFY ...... 11
# EXPOSE ............. 12
# GRAPHICS_EXPOSURE .. 13
# NO_EXPOSURE ........ 14
# VISIBILITY_NOTIFY .. 15
# CREATE_NOTIFY ...... 16
# DESTROY_NOTIFY ..... 17
# UNMAP_NOTIFY ....... 18
# MAP_NOTIFY ......... 19
# MAP_REQUEST ........ 20
# REPARENT_NOTIFY .... 21
# CONFIGURE_NOTIFY ... 22
# CONFIGURE_REQUEST .. 23
# GRAVITY_NOTIFY ..... 24
# RESIZE_REQUEST ..... 25
# CIRCULATE_NOTIFY ... 26
# CIRCULATE_REQUEST .. 27
# PROPERTY_NOTIFY .... 28
# SELECTION_CLEAR .... 29
# SELECTION_REQUEST .. 30
# SELECTION_NOTIFY ... 31
# COLORMAP_NOTIFY .... 32
# CLIENT_MESSAGE ..... 33
# MAPPING_NOTIFY ..... 34
# GE_GENERIC ......... 35