#!/bin/sh

xbps-install gnupg mutt offlineimap mblaze

gpg --gen-key

gpg -r anon@cron.world -e ~/app/sec/mutt/creds-gmx
gpg -r anon@cron.world -e ~/app/sec/mutt/creds-cron

rm ~/app/sec/mutt/creds-{gmx,cron}
